### PR TITLE
Bar chart redraws upon dataset change

### PR DESCRIPTION
**Pull request by sbatson5**
Bar charts redraw on dataset length update.  Unit test included.

### CODE REVIEW

**Comment by aomra015** [comment]
This looks good. The build is failing because of an issue that is now fixed on master. Can you rebase from master to get the latest code? Thank you.

**Comment by sbatson5** [comment]
@aomra015 Thank you for taking a look.  Rebased and pushed.

**Comment by jgelens** [comment]
Would be great if you can release a new version for this change.

**Comment by aomran** [comment]
@jgelens I've released v2.0.5 -- thanks for the reminder!

**Comment by jgelens** [comment]
Thanks a lot!

**Pull request merged**
