### PR TITLE
Version 3

### PR DESCRIPTION
**Pull request by aomran**
* Upgrades ember-cli to v2.5
* Upgrades chartjs to v.2.1.1
* This requires a major version bump because chartjs made major changes to their api.
* This version makes the addon a small wrapper for chartjs by removing code that was added to make legends and auto-updating work.

### CODE REVIEW

**Comment by chvonrohr** [comment]
👍 💯  thanks

**Comment by abobwhite** [comment]
Awesome. I'd love to see this merged so I can see if it fixes an issue with the legend repeating itself anytime bound data is changed. I don't want to create a new issue without trying this first. Any reservations with merging it?

**Comment by abobwhite** [comment]
I figured it out that I needed my legendTemplate to include ```class="<%=name.toLowerCase()%>-legend"```. Thanks for creating and maintaining this repo. Looking forward to using the newest version.

**Comment by DiederikvandenB** [comment]
Horizontal bars do not yet work correctly with this PR. I 
image

As you can see, the canvas is way to tall and the border behaviour seems like it is still expecting it to be a vertical bar graph.

**Comment by CBarraford** [comment]
What needs to be done before this PR can be merged??

**Comment by jelhan** [comment]
I'm getting an exception thrown when running tests in edge: `Unable to get property 'currentStyle' of undefined or null reference`. Therefore updated to latest Chart.js release (#59) but that doesn't fixed the issue.

**Comment by jelhan** [comment]
#60 fixes the issues in edge by providing a wrapper.

**Comment by erkie** [comment]
@aomran how can we help you get this merged?

**Comment by derekdowling** [comment]
Hello @aomran any thing that needs to be done to get this merged?

**Pull request merged**
