### PR TITLE
Use Chart.js from NPM instead of Bower

### LINKED ISSUE #69: Remove chartsjs from bower dependencies
Bower is basically an obsolete package manager as the JS world transitions to npm/yarn. Please consider removing dropzone from bower dependencies and grabbing it with npm instead.

### PR DESCRIPTION
**Pull request by tylergets**
Fixes #69

### CODE REVIEW

**Comment by elwayman02** [comment]
Reference: #59 & #67

**Comment by aomran** [comment]
thank you @tylergets

**Comment by elwayman02** [comment]
Awesome! Looking forward to the new version to be released. Thanks everyone!

**Comment by tylergets** [comment]
@aomran mind doing a version bump? We would love to get this into production

**Comment by aomran** [comment]
@tylergets done

**Pull request merged**
