### PR TITLE
Ember 3.13

### PR DESCRIPTION
**Pull request by rwwagner90**
This should also fix testem and gpu issues. I updated travis to use ember-try, as well, so we can test against the recommended Ember versions.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@aomran any chance we could get this in? Looks like we need to restart the travis build.

**Comment by rwwagner90** [comment]
@aomran would you mind restarting the travis build please?

**Comment by aomran** [comment]
@rwwagner90 I restarted the Travis build.

**Comment by aomran** [comment]
@rwwagner90 thank you for this pr 👍

**Comment by rwwagner90** [comment]
You're welcome!

**Comment by aomran** [comment]
I pushed an update to npm

**Pull request merged**
