### PR TITLE
Nested Addon / Ember Engines Support

### PR DESCRIPTION
**Pull request by devotox**
- Also upgraded to 2.6.0 Ember Charts

### CODE REVIEW

**Comment by aomran** [comment]
@devotox sorry I haven't looked at this. Do you know if nested add-ons are still a problem with the most current version of the codebase? I recently modified the `index.js` implementation. thanks.

**Comment by devotox** [comment]
That probably does work but it might not work for infinitely nested Ember Addons. The way i wrote it seems to be the community supported way to fully protect around infinite nesting and every ember version

https://github.com/simplabs/ember-simple-auth/blob/master/index.js

Also do you think we can look at removing bower as the rest of the ember world are going towards just NPM and Yarn

**Comment by aomran** [comment]
@devotox thanks for the contribution and sorry for my slow response. Do you mind fixing the conflicts? I'll merge after that.

**Comment by devotox** [comment]
Merge conflicts fixed @aomran

**Comment by devotox** [comment]
Ha but there is a problem now since you no longer use bower ... hold on

**Comment by devotox** [comment]
This has now been fixed to also include Fastboot Support and move the retrieval of Chart JS from the node modules folder  while updating all the packages to latest Ember 2.14 versions

**Comment by aomran** [comment]
thanks @devotox

**Pull request merged**
